version: '3.7'

services:
  db:
    image: mysql:8.0.24
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tdd_otp
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  redis:
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379